name: todo_app_sqflite
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2
  provider: ^6.1.2
  path_provider: ^2.1.2
  path: ^1.9.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/MyFont-Medium.ttf
